name: autodiscovery
dependencies:
  - python=3.11
  - streamlit=1.37.1
  - pandas=1.5.3
  - matplotlib=3.10
  - pip
  - pip:
    - IPython==8.26.0
    - pyautogen[openai]==0.8
    - scikit-learn
    - scipy
    - statsmodels
    - h5py
    - boto3
